//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job_Tab
    {
        public int Job_Id { get; set; }
        public int Comp_Reg_Id { get; set; }
        public int State_Id { get; set; }
        public int Dist_Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Status { get; set; }
        public string Qualification { get; set; }
        public string Skills { get; set; }
        public System.DateTime DOP { get; set; }
        public string Location { get; set; }
        public string Salary { get; set; }
        public int Experience { get; set; }
    }
}
