//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Login_Tab
    {
        public int Log_Id { get; set; }
        public int Reg_Id { get; set; }
        public string Username { get; set; }
        public string password { get; set; }
        public string Log_Type { get; set; }
    }
}
